title: Dipika Sharma
logo: https://github.com/Dipika03/Dipika03.github.io/blob/main/Images/1516645062485.jpeg
description: Skilled data analyst with 15+ years of experience in collecting, organizing, interpreting and analyzing data for driving business solutions. In free time love doing painting.
show_downloads: true
theme: jekyll-theme-minimal
