title: Dipika Sharma
#logo: /assets/img/headshot_circle.png
description: Skilled data analyst with 15+ years of experience in collecting, organizing, interpreting and analyzing data for driving business solutions. In free time love doing painting.
show_downloads: true
theme: jekyll-theme-minimal
